### ISSUE TITLE
Using multiple sessions in parallel can corrupt kubie state.json

### ISSUE THREAD

**Issue by TyBrown** [kubie-org/kubie#66]
Hi there;

New kubie user here. I use iTerm2 and multiple session panes in the same window. Kubie has been a life saver, allowing me to have a pane for each cluster I'm working on and work on them in parallel using iTerm2's Broadcast Input feature. However, I ran into an issue today where I ran `kubie ns foo` in parallel that caused all of the kubie sessions to update the state.json file at the same time, which corrupted it.

The error I received later on when I tried to enter a context in a new terminal window was not super helpful in pointing me to what the underlying problem was either:
```
$ kubie ctx foo
Error: trailing characters at line 1 column 102
```

I was able to find the state.json file and simply delete it, which allowed kubie to continue working for me again.

I think kubie probably needs some sort of file lock or some other mechanism to avoid parallel invocations of kubie from corrupting the state.json file, and I think kubie could provide a little more context around that particular error, perhaps even printing the path to the state.json file it's encountering the error in as well. (I had originally looked for it at `~/.local/share/kubie/state.json`, but on my Mac the state.json was actually in `~/Library/Application Support/kubie/state.json`.

I've been looking for an excuse to learn Rust, so this may be it... but figured I'd start by raising an issue in case someone else is able/wants to look at it before I can get around to learning enough to figure it out and submit a PR.

Cheers,
Ty

**Comment by sbstp** [comment]
Hey, this is definitely not something I expected to happen 😄. I did a quick check and it seems that there's a library with file locking APIs we could use: https://docs.rs/fs2/0.4.3/fs2/trait.FileExt.html

Note that file locking can be unreliable at times, for instance on networked file systems like NFS and CIFS/Samba they don't work well at all. I had problems with running SQLite on Samba a while back. But I guess it's unlikely that the `state.json` would be on a network file system.

Let me know if you try to tackle it, otherwise I can do it or I might have a work buddy that would be interested.

**Comment by TyBrown** [comment]
One of my friends pointed out the locking issue as well, and mentioned that perhaps a better approach would be to write to a temp file, then perform a file move so that it's atomic. It'd mean that parallel invocations would still fail to write all of the versions... only the last write would win, but at least then there's no locking/NFS concerns to worry about.
