### ISSUE TITLE
Error: No such file or directory

### ISSUE THREAD

**Issue by diego-maravankin** [kubie-org/kubie#69]
Hi guys! 
I am using kubie 0.13.3, but I cannot seem to get it working. When I try to swit to a new context, it fails with "no such file or directory".

```
$ kubie --version
kubie 0.13.3
$ kubie ctx
Error: No such file or directory (os error 2)
```

I went back to 0.13.2 and it works properly. If you let me know how to increase the log level, I can share more information.

**Comment by TyBrown** [comment]
Hi @diego-maravankin ... I'll take a look at this today. Just so I can narrow down the testing, which Operating System are you using?

**Comment by TyBrown** [comment]
Hi @diego-maravankin ... we've found the bug that I introduced in 0.13.3 (https://github.com/sbstp/kubie/pull/67#pullrequestreview-614463264 for more details if you're interested). The good news is that once you've run kubie once on 0.13.2, you should be able to upgrade to 0.13.3 with no problems, the bug only seems to occur on a fresh install, which is why I missed it while I was testing. I'm terribly sorry for the troubles. @sbstp has a fix already in #70.

**Comment by diego-maravankin** [comment]
Hi @TyBrown! I just saw your response. I am using Ubuntu 20.04 amd64, I am using the precompiled binary. 

I tried 0.13.3 after using 0.13.2, but still get the error. Let me know if you need me to do any further tests.

**Comment by diego-maravankin** [comment]
That fixed it. Thanks @sbstp! I'll update to 0.13.4 when its available.

**Comment by rubensayshi** [comment]
hmm @sbstp this seems to be occuring for me with v0.16.0 ?
